[project]
name = "yuketang-video"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "browser-cookie3>=0.20.1",
    "tqdm>=4.67.1",
]
